# Typos configuration file
#
# Info:    https://github.com/marketplace/actions/typos-action
# Install: brew install typos-cli
# Install: conda install typos
# Run:     typos -c .github/_typos.toml

[files]
extend-exclude = [
    "_typos.toml",
    "package-lock.json",
    "*.bicep",
    "encoder.json",
    "vocab.bpe",
    "GPT3TokenizerTests.cs",
    "CodeTokenizerTests.cs",
    "test_code_tokenizer.py"
]

[default]
extend-ignore-re = [
    # Line ignore with trailing (# | //) spellchecker:disable-line
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
]

[default.extend-words]
ACI = "ACI" # Azure Container Instance
AKS = "AKS" # Azure K8s Service

[default.extend-identifiers]
ags = "ags" # Azure Graph Service

[type.jupyter]
extend-ignore-re = [
    '"[A-Fa-f0-9]{8}"', # cell id strings
]

[type.msbuild]
extend-ignore-re = [
    'Version=".*"', # ignore package version numbers
]
