{{- if and (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).enabled .Values.webapp.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "q-pilot.webapp.fullname" . }}
  labels:
    {{- include "q-pilot.webapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "q-pilot.webapp.fullname" . }}
  minReplicas: {{ (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).minReplicas }}
  maxReplicas: {{ (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).maxReplicas }}
  metrics:
    {{- if (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ (mergeOverwrite (deepCopy .Values.autoscaling) (deepCopy .Values.fe.autoscaling) .Values.webapp.autoscaling).targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
