{{- if and (mergeOverwrite (deepCopy .Values.ingress) (deepCopy .Values.fe.ingress) .Values.webapp.ingress).enabled .Values.webapp.enabled }}
{{- $fullName := include "q-pilot.webapp.fullname" . -}}
{{- $svcPort := (default .Values.service.port (default .Values.fe.service.port .Values.webapp.service.port)) -}}
{{- if and .Values.webapp.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.webapp.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.webapp.ingress.annotations "kubernetes.io/ingress.class" .Values.webapp.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "q-pilot.webapp.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.ingress) (deepCopy .Values.fe.ingress) .Values.webapp.ingress).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (default .Values.ingress.className (default .Values.fe.ingress.className .Values.webapp.ingress.className )) (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ (default .Values.ingress.className (default .Values.fe.ingress.className .Values.webapp.ingress.className )) }}
  {{- end }}
  {{- if (default .Values.ingress.tls (default .Values.fe.ingress.tls .Values.webapp.ingress.tls)) }}
  tls:
    {{- range (mergeOverwrite (deepCopy .Values.ingress) (deepCopy .Values.fe.ingress) .Values.webapp.ingress).tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with (first .hosts) }}
      secretName: {{ . }}-certificate
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range (mergeOverwrite (deepCopy .Values.ingress) (deepCopy .Values.fe.ingress) .Values.webapp.ingress).hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
