{{- if .Values.webapp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "q-pilot.webapp.fullname" . }}
  labels:
    {{- include "q-pilot.webapp.labels" . | nindent 4 }}
spec:
  type: {{ (default .Values.service.type (default .Values.fe.service.type .Values.webapp.service.type)) }}
  ports:
    - port: {{ (default .Values.service.port (default .Values.fe.service.port .Values.webapp.service.port)) }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "q-pilot.webapp.selectorLabels" . | nindent 4 }}
{{- end }}
