{{- if and (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).enabled .Values.webapi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "q-pilot.webapi.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).clientId | quote }}
    keyvaultName: {{ (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).vaultName }}
    tenantId: {{ (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).tenantId | quote }}
    objects: |
      array:
        {{- range (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).secrets }}
        - |
          objectName: {{ . }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ include "q-pilot.webapi.fullname" . }}-secret
      type: Opaque
      data:
      {{- range (mergeOverwrite (deepCopy .Values.secretProviderClass) (deepCopy .Values.be.secretProviderClass) .Values.webapi.secretProviderClass).secrets }}
      - objectName: {{ . }}
        key: {{ . }}
      {{- end }}
{{- end }}
