image:
  tag: "dev"

###############
# webapp specific values
###############

webapp:
  image:
    tag: "dev"
###############
# webapi specific values
###############

webapi:
  image:
    tag: "dev"
