# To fix locally Run: dotnet csharpier .
name: Validate Code Style
on:
  pull_request:
    branches: [ main ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: csharpier formatting
        run: |
          dotnet tool restore
          dotnet csharpier --check webapi
