# To fix locally Run: dotnet csharpier .
name: Validate Code Style
on:
  pull_request:
    branches: [ main ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: chsharpier formatting
        working-directory: ./webapi
        run: |
          dotnet tool restore
          dotnet csharpier --config-path ../../.editorconfig --check .
